# Generated by Django 4.2.5 on 2023-09-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
